Move vuetify-loader to dependencies from devDependencies
The vuetify-loader package is required by index.js, so when attempting to build a project which includes vue-cli-plugin-vuetify will fail with the error as shown below if the package isn't included in the project.

```
$ yarn serve
yarn run v1.10.1
$ vue-cli-service serve
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'vuetify-loader/lib/plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/my-project/node_modules/vue-cli-plugin-vuetify/index.js:1:91)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```